const ERROR_CODE_BADREQ = 400;
const ERROR_CODE_NOTFOUND = 404;
const ERROR_CODE_DB = 500;
const ERROR_CODE_UNAUTH = 401;
const EROR_CODE_CONFLICT = 409;
const EROR_CODE_FORBIDDEN = 403;

module.exports = {
  ERROR_CODE_BADREQ,
  ERROR_CODE_NOTFOUND,
  ERROR_CODE_DB,
  ERROR_CODE_UNAUTH,
  EROR_CODE_CONFLICT,
  EROR_CODE_FORBIDDEN,
};
